### ISSUE TITLE
Path with '~' throw FileNotFoundException

### ISSUE THREAD

**Issue by ttben** [mauricioaniche/repodriller#107]
`new CSVFile("~/Desktop/q2.csv")` will output : 

```
14:25:10 ERROR This study threw an exception:
java.lang.RuntimeException: java.io.FileNotFoundException: ~/Desktop/q2.csv (No such file or directory)
	at org.repodriller.persistence.csv.CSVFile.<init>(CSVFile.java:43)
	at org.repodriller.persistence.csv.CSVFile.<init>(CSVFile.java:36)
	at tutorial.q2.Q2Study.execute(Q2Study.java:22)
	at org.repodriller.RepoDriller.start(RepoDriller.java:61)
	at tutorial.q2.Q2Study.main(Q2Study.java:14)
Caused by: java.io.FileNotFoundException: ~/Desktop/q2.csv (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.repodriller.persistence.csv.CSVFile.<init>(CSVFile.java:41)
	... 4 more
```

whereas `new CSVFile("/Users/benjaminbenni/Desktop/q2.csv")` works fine.

**Comment by davisjam** [comment]
Good catch, should be fixed. Let's try something like [this](https://stackoverflow.com/a/7163446).

**Comment by ttben** [comment]
Sounds good to me :)
I thought `Java` itself would have done that.
I don't understand why/how I didn't have the issue on other projects.. 😐

**Comment by davisjam** [comment]
Google suggests that Java does not do this. Perhaps we are just lazier than average ;-)

**Comment by ttben** [comment]
Haha I didn't imply that :P
But if `Java` checks `\` and `/` why not `~` and so on.
Thanks!

**Comment by mauricioaniche** [comment]
Wow, I always thought that worked. For now, I just provide a short note about it in the docs: https://github.com/mauricioaniche/repodriller/blob/master/README.md
